# rvm-ruby: install Ruby using RVM

FROM foundationdb/rvm

MAINTAINER "fdb-boston@foundationdb.com"

RUN bash -c "source /usr/local/rvm/scripts/rvm && rvm install ruby && rvm alias create default ruby"
